# Site settings
title: David Chisnall
author: David Chisnall
# This is the author that will be used for highlighting the author in
# publication entries.
pubauthor: David Chisnall
url: "http://www.cl.cam.ac.uk" 
baseurl: /~dc552
createdyear: 2004
destination: public_html
collections:
  projects:
    output: false
  people:
    output: false
# Build settings
markdown: kramdown
kramdown: 
  toc_levels: "2,3" 
scholar:
  bibliography_template: bib
  style: ./_bibliography/cl-pubs
  bibliography: publications.bib
  sort_by: year
  order: descending
