# Site settings
title: CADETS
url: "http://www.cl.cam.ac.uk/"
baseurl: /research/security/cadets
createdyear: 2015
destination: cadets
collections:
  projects:
    output: false
  people:
    output: false
# Build settings
markdown: kramdown
kramdown: 
  toc_levels: "2,3" 
scholar:
  bibliography_template: bib
  style: ./_bibliography/cl-pubs
  bibliography: publications.bib
  sort_by: year
  order: descending
